version: "3.7"

services:
  jekyll:
    image: loustler/jekyll:ruby-2.6
    ports:
      - "4000:4000"
    volumes:
      - type: bind
        source: ./
        target: /home/rubyuser
    command: bash -c "bundle install && bundle exec jekyll serve --host 0.0.0.0"